# Generated by Django 5.2.8 on 2025-12-26 10:19

import datetime
import django.db.models.deletion
import marania_invoice_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('current_invoice_number', models.PositiveIntegerField(default=1)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('finance_year', models.CharField(default=marania_invoice_app.models.current_indian_financial_year, max_length=20)),
                ('company_title', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPriceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('invoice_number', models.CharField(max_length=50, null=True, unique=True)),
                ('customer_code', models.CharField(max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ship_to_customer_code', models.CharField(max_length=50, null=True)),
                ('ship_to_customer_name', models.CharField(max_length=100, null=True)),
                ('ship_to_customer_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('ship_to_customer_address', models.TextField(blank=True, null=True)),
                ('ship_to_customer_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('ship_to_customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dispatched_through', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_bill_to', models.TextField(blank=True, null=True)),
                ('address_ship_to', models.TextField(blank=True, null=True)),
                ('is_within_state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PriceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('customer_group', models.CharField(max_length=100)),
                ('sequence_id', models.PositiveIntegerField()),
                ('mesh_size_start', models.CharField(max_length=5)),
                ('mesh_size_end', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
                'ordering': ['sequence_id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_spec', models.CharField(blank=True, max_length=200, null=True)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('item_mesh_size', models.CharField(blank=True, max_length=20, null=True)),
                ('item_mesh_depth', models.CharField(blank=True, max_length=20, null=True)),
                ('item_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_colour', models.CharField(blank=True, max_length=100, null=True)),
                ('item_hsn_code', models.CharField(blank=True, max_length=10, null=True)),
                ('item_gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_total_with_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marania_invoice_app.invoice', to_field='invoice_number')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('displayname', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, help_text='GST percentage (e.g. 9.00)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='materials', to='marania_invoice_app.parties')),
            ],
        ),
        migrations.AddField(
            model_name='parties',
            name='roles',
            field=models.ManyToManyField(blank=True, to='marania_invoice_app.partyrole'),
        ),
        migrations.CreateModel(
            name='CustomerPriceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_included', models.BooleanField(default=False)),
                ('colour_extra_price', models.FloatField(default=0)),
                ('small_mesh_size_extra_price', models.FloatField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_items', to='marania_invoice_app.parties')),
                ('price_catalog', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_catalog_items', to='marania_invoice_app.pricecatalog')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn', models.CharField(blank=True, max_length=20, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marania_invoice_app.materials')),
            ],
        ),
        migrations.AddField(
            model_name='pricecatalog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='marania_invoice_app.product'),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_place', models.CharField(blank=True, max_length=50, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transporter_gst', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_name_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default_transport', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transportations', to='marania_invoice_app.parties')),
            ],
        ),
    ]
