# Generated by Django 5.2.8 on 2025-12-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transportations', to='marania_invoice_app.parties'),
        ),
    ]
