# Generated by Django 5.2.1 on 2025-11-09 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0002_invoice_contact_invoice_customer_address_bill_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='gst',
            new_name='customer_gst',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
