# Generated by Django 5.2.8 on 2025-12-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0002_alter_transportation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='roles',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='marania_invoice_app.partyrole'),
        ),
    ]
