# Generated by Django 5.2.1 on 2025-11-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0003_rename_gst_invoice_customer_gst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='contact',
            new_name='customer_contact',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='email',
            new_name='customer_email',
        ),
    ]
