# Generated by Django 5.2.8 on 2025-12-27 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0003_alter_parties_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='marania_invoice_app.materials', to_field='code'),
        ),
    ]
