# Generated by Django 5.2.8 on 2025-12-27 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0004_alter_product_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecatalog',
            options={},
        ),
        migrations.AlterField(
            model_name='pricecatalog',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pricecatalogs', to='marania_invoice_app.product', to_field='code'),
        ),
    ]
