# Generated by Django 5.2.1 on 2025-11-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0004_rename_contact_invoice_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
