# Generated by Django 5.2.1 on 2025-11-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0005_alter_invoice_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_spec', models.CharField(blank=True, max_length=200, null=True)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('item_mesh_size', models.CharField(blank=True, max_length=20, null=True)),
                ('item_mesh_depth', models.CharField(blank=True, max_length=20, null=True)),
                ('item_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marania_invoice_app.invoice', to_field='invoice_number')),
            ],
        ),
        migrations.DeleteModel(
            name='invoiceitems',
        ),
    ]
