# Generated by Django 5.2.8 on 2025-12-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0005_alter_pricecatalog_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPriceMap',
        ),
    ]
