# Generated by Django 5.2.8 on 2025-12-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0006_delete_customerpricemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpricecatalog',
            name='price_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
