# Generated by Django 5.2.8 on 2025-11-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0006_invoiceitem_delete_invoiceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
