# Generated by Django 5.2.8 on 2025-11-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0007_invoiceitem_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice_number',
        ),
    ]
