# Generated by Django 5.2.1 on 2025-11-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0008_remove_invoiceitem_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
