# Generated by Django 5.2.8 on 2025-12-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0008_companysettings_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transporter_gst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle_name_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
