# Generated by Django 5.2.8 on 2025-12-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0009_invoice_transporter_gst_invoice_vehicle_name_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='colour_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
