# Generated by Django 5.2.1 on 2025-11-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0009_configuration_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_place', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default_transport', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marania_invoice_app.customer', to_field='code')),
            ],
        ),
    ]
