# Generated by Django 5.2.1 on 2025-11-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0010_transportation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='default_delivery_location',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_delivery_transport',
        ),
    ]
