# Generated by Django 5.2.8 on 2025-12-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0010_companysettings_colour_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='small_mesh_size_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
