# Generated by Django 5.2.1 on 2025-11-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0011_remove_customer_default_delivery_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportation',
            old_name='vehicle_name',
            new_name='transporter_name',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='transport_gst',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='transportation',
            name='transporter_gst',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='vehicle_name_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
