# Generated by Django 5.2.8 on 2025-12-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0011_companysettings_small_mesh_size_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='company_gst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company_state_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
