# Generated by Django 5.2.8 on 2025-12-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0012_companysettings_company_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='company_gst',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='company_state',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='company_state_code',
        ),
    ]
