# Generated by Django 5.2.8 on 2025-12-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0013_remove_companysettings_company_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='company_gst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
