# Generated by Django 5.2.1 on 2025-11-15 04:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0014_pricelist_created_at_pricelist_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='product',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marania_invoice_app.product', to_field='code'),
            preserve_default=False,
        ),
    ]
