# Generated by Django 5.2.1 on 2025-11-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0015_pricelist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
