# Generated by Django 4.2.27 on 2026-02-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0016_excelsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
