# Generated by Django 5.2.1 on 2025-11-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0016_delete_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='mesh_size_end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='mesh_size_start',
            field=models.IntegerField(),
        ),
    ]
