# Generated by Django 5.2.1 on 2025-11-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0017_alter_pricelist_mesh_size_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='mesh_size_end',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='mesh_size_start',
            field=models.CharField(max_length=5),
        ),
    ]
