# Generated by Django 4.2.27 on 2026-02-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0018_invoice_cgst_amount_invoice_gross_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quantity_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
