# Generated by Django 5.2.1 on 2025-11-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0018_alter_pricelist_mesh_size_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_address_bill_to',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_address_ship_to',
            new_name='ship_to_customer_address',
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_customer_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_customer_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_customer_gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
