# Generated by Django 4.2.27 on 2026-02-18 10:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0019_invoice_quantity_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='quantity_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
