# Generated by Django 5.2.1 on 2025-11-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0019_rename_customer_address_bill_to_invoice_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ship_to_customer_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
