# Generated by Django 4.2.27 on 2026-04-05 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0020_alter_invoice_quantity_total_alter_invoice_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='materials', to='marania_invoice_app.parties'),
        ),
    ]
