# Generated by Django 5.2.1 on 2025-11-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0020_alter_invoice_customer_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(max_length=10, unique=True)),
                ('current_invoice_number', models.IntegerField(default=0)),
            ],
        ),
    ]
