# Generated by Django 5.2.1 on 2025-11-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0021_runningnumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunningNumber',
            new_name='SystemDynamicInfo',
        ),
    ]
