# Generated by Django 4.2.27 on 2026-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0022_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mesh_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity_unit',
            field=models.CharField(choices=[('KGs', 'KGs'), ('Bag', 'Bag')], default='Bag', max_length=10),
        ),
    ]
