# Generated by Django 5.2.1 on 2025-11-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0022_rename_runningnumber_systemdynamicinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('current_invoice_number', models.PositiveIntegerField(default=1)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company_title', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.DeleteModel(
            name='SystemDynamicInfo',
        ),
    ]
