# Generated by Django 4.2.27 on 2026-06-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0023_alter_order_mesh_size_alter_order_quantity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='piece_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
