# Generated by Django 5.2.8 on 2025-11-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0023_companysettings_delete_systemdynamicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='finance_year',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
    ]
