# Generated by Django 5.2.8 on 2025-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0024_companysettings_finance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_hsn_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_total_with_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='finance_year',
            field=models.CharField(default='25-26', max_length=20),
        ),
    ]
