# Generated by Django 5.2.8 on 2025-12-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0025_invoiceitem_item_gst_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceList',
            new_name='PriceCatalog',
        ),
    ]
