# Generated by Django 5.2.8 on 2025-12-07 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0026_rename_pricelist_pricecatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPriceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_included', models.BooleanField(default=False)),
                ('colour_extra_price', models.FloatField(default=0)),
                ('small_mesh_size_extra_price', models.FloatField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_items', to='marania_invoice_app.customer')),
                ('price_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_catalog_items', to='marania_invoice_app.pricecatalog')),
            ],
            options={
                'verbose_name': 'Customer Price Catalog',
                'verbose_name_plural': 'Customer Price Catalogs',
                'db_table': 'customer_price_catalog',
            },
        ),
    ]
