# Generated by Django 4.2.27 on 2026-06-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0026_alter_order_options_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='colour',
            field=models.CharField(default='White', max_length=50),
        ),
    ]
