# Generated by Django 5.2.8 on 2025-12-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0027_customerpricecatalog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Parties',
        ),
    ]
