# Generated by Django 5.2.8 on 2025-12-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0028_rename_customer_parties'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='parties',
            name='roles',
            field=models.ManyToManyField(related_name='roles', to='marania_invoice_app.partyrole'),
        ),
    ]
