# Generated by Django 4.2.27 on 2026-06-28 23:20

from django.db import migrations, models
from django.db.models import F


def populate_order_sequence(apps, schema_editor):
    Order = apps.get_model('marania_invoice_app', 'Order')
    Order.objects.all().update(order_sequence=F('order_key'))


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0028_order_sequence_and_pk'),
    ]

    operations = [
        migrations.RunPython(populate_order_sequence, migrations.RunPython.noop),
    ]
