# Generated by Django 5.2.8 on 2025-12-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0029_partyrole_parties_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='roles',
            field=models.ManyToManyField(related_name='parties', to='marania_invoice_app.partyrole'),
        ),
        migrations.AlterField(
            model_name='partyrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partyrole',
            name='role',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
