# Generated by Django 4.2.27 on 2026-07-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0029_populate_order_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_of_pcs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
