# Generated by Django 4.2.27 on 2026-07-12 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0030_no_of_pcs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_size', models.IntegerField(blank=True, null=True)),
                ('mesh_depth', models.CharField(blank=True, max_length=50, null=True)),
                ('salvage', models.CharField(blank=True, max_length=255, null=True)),
                ('piece_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('colour', models.CharField(default='White', max_length=50)),
                ('no_of_pcs', models.IntegerField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='marania_invoice_app.order')),
            ],
        ),
    ]
