# Generated by Django 5.2.8 on 2025-12-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0030_alter_parties_roles_alter_partyrole_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='roles',
            field=models.ManyToManyField(blank=True, to='marania_invoice_app.partyrole'),
        ),
        migrations.AlterField(
            model_name='partyrole',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
