# Generated by Django 4.2.27 on 2026-07-12 04:28

from django.db import migrations


def copy_spec_data(apps, schema_editor):
    Order = apps.get_model('marania_invoice_app', 'Order')
    OrderSpecification = apps.get_model('marania_invoice_app', 'OrderSpecification')
    for order in Order.objects.iterator():
        OrderSpecification.objects.create(
            order=order,
            mesh_size=order.mesh_size,
            mesh_depth=order.mesh_depth,
            salvage=order.salvage,
            piece_weight=order.piece_weight,
            colour=order.colour or 'White',
            no_of_pcs=order.no_of_pcs,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0031_order_specification'),
    ]

    operations = [
        migrations.RunPython(copy_spec_data, migrations.RunPython.noop),
    ]
