# Generated by Django 4.2.27 on 2026-07-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0032_copy_spec_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mesh_depth',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mesh_size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='no_of_pcs',
        ),
        migrations.RemoveField(
            model_name='order',
            name='piece_weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='salvage',
        ),
    ]
