# Generated by Django 5.2.8 on 2025-12-14 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0033_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricecatalog',
            name='twine_code',
        ),
    ]
