# Generated by Django 4.2.27 on 2026-07-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0033_remove_spec_from_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderspecification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='marania_invoice_app.order'),
        ),
    ]
