# Generated by Django 5.2.8 on 2025-12-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0034_remove_pricecatalog_twine_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
