# Generated by Django 4.2.27 on 2026-07-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0034_alter_orderspecification_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_unit',
            field=models.CharField(choices=[('KG', 'KG'), ('Bag', 'Bag')], default='Bag', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('ProductionQueue', 'Production Queue'), ('InProduction', 'In Production'), ('ProductionCompleted', 'Production Completed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('OnHold', 'On Hold'), ('Rejected', 'Rejected')], default='Ordered', max_length=30),
        ),
    ]
