# Generated by Django 4.2.27 on 2026-07-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0035_alter_order_quantity_unit_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('ProductionQueue', 'P Queue'), ('InProduction', 'In Prod'), ('ProductionCompleted', 'P Completed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('OnHold', 'On Hold'), ('Rejected', 'Rejected')], default='Ordered', max_length=30),
        ),
    ]
