# Generated by Django 5.2.8 on 2025-12-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0035_invoiceitem_item_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='customer',
            field=models.ForeignKey(db_column='customer_code', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marania_invoice_app.parties', to_field='code'),
        ),
    ]
