# Generated by Django 4.2.27 on 2026-07-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0036_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
