# Generated by Django 5.2.8 on 2025-12-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0037_alter_transportation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marania_invoice_app.parties', to_field='code'),
        ),
    ]
