# Generated by Django 4.2.27 on 2026-07-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0037_order_last_status_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_key', models.AutoField(primary_key=True, serialize=False)),
                ('sales_sequence', models.IntegerField(default=0)),
                ('order_no', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('twine', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('initial_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('processed_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('PARTIALLY_PAID', 'PARTIALLY PAID'), ('PENDING', 'PENDING'), ('NO_PAYMENT', 'NO PAYMENT'), ('ON_HOLD_STOCK', 'ON HOLD(Item On Stock)'), ('ON_HOLD_PROCESSING', 'ON HOLD(PROCESSING)')], default='PENDING', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-order_date', '-sales_sequence'],
            },
        ),
        migrations.CreateModel(
            name='SalesSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_size', models.IntegerField(blank=True, null=True)),
                ('mesh_depth', models.CharField(blank=True, max_length=50, null=True)),
                ('salvage', models.CharField(blank=True, max_length=255, null=True)),
                ('piece_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('colour', models.CharField(default='White', max_length=50)),
                ('no_of_pcs', models.IntegerField(blank=True, null=True)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='marania_invoice_app.sales')),
            ],
        ),
    ]
