# Generated by Django 5.2.8 on 2025-12-25 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0038_alter_transportation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='marania_invoice_app.parties', to_field='code'),
        ),
    ]
