# Generated by Django 4.2.27 on 2026-07-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0038_sales_salesspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderspecification',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='marania_invoice_app.sales'),
        ),
        migrations.AlterField(
            model_name='orderspecification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='marania_invoice_app.order'),
        ),
    ]
