# Generated by Django 4.2.27 on 2026-07-12 09:26

from django.db import migrations


def migrate_sales_specs(apps, schema_editor):
    SalesSpecification = apps.get_model('marania_invoice_app', 'SalesSpecification')
    OrderSpecification = apps.get_model('marania_invoice_app', 'OrderSpecification')
    for old_spec in SalesSpecification.objects.iterator():
        OrderSpecification.objects.create(
            sales_id=old_spec.sales_id,
            mesh_size=old_spec.mesh_size,
            mesh_depth=old_spec.mesh_depth,
            salvage=old_spec.salvage,
            piece_weight=old_spec.piece_weight,
            colour=old_spec.colour,
            no_of_pcs=old_spec.no_of_pcs,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0039_orderspecification_sales_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_sales_specs, migrations.RunPython.noop),
    ]
