# Generated by Django 4.2.27 on 2026-07-12 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0041_delete_sales_specification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-sales_entry_date', '-sales_sequence']},
        ),
        migrations.RemoveField(
            model_name='orderspecification',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total_price',
        ),
        migrations.AddField(
            model_name='sales',
            name='colour',
            field=models.CharField(default='White', max_length=50),
        ),
        migrations.AddField(
            model_name='sales',
            name='piece_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='piece_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sales',
            name='speification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
