# Generated by Django 4.2.27 on 2026-07-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0042_alter_sales_options_remove_orderspecification_sales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('total_received', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Cheque', 'Cheque'), ('UPI', 'UPI')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('allocation_status', models.CharField(choices=[('Unallocated', 'Unallocated'), ('Partially Allocated', 'Partially Allocated'), ('Fully Allocated', 'Fully Allocated')], default='Unallocated', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_receipts', to='marania_invoice_app.parties')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocation_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_allocations', to='marania_invoice_app.invoice', to_field='invoice_number')),
                ('payment', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='marania_invoice_app.paymentreceipt')),
            ],
            options={
                'ordering': ['-allocation_date'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('opening_balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_date', models.DateField()),
                ('account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opening_balances', to='marania_invoice_app.parties')),
            ],
            options={
                'ordering': ['-opening_date'],
            },
        ),
    ]
