# Generated by Django 4.2.27 on 2026-07-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0043_paymentreceipt_paymentallocation_openingbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid'), ('WrittenOff', 'Written Off'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
