# Generated by Django 4.2.27 on 2026-07-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0044_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='transaction_type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Adjustment(Cr)', 'Adjustment(Cr)'), ('Adjustment(Dr)', 'Adjustment(Dr)')], default='Payment', max_length=20),
        ),
    ]
