# Generated by Django 4.2.27 on 2026-07-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0045_paymentreceipt_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_date', models.DateField()),
                ('expense_category', models.CharField(choices=[('Employee Salary', 'Employee Salary'), ('Mechanic Salary', 'Mechanic Salary'), ('Miscellaneous', 'Miscellaneous'), ('Electricity', 'Electricity'), ('Spare Parts', 'Spare Parts'), ('Transportation', 'Transportation'), ('Net Processing', 'Net Processing')], max_length=50)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], default='Cash', max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partially Paid', 'Partially Paid')], default='Pending', max_length=20)),
                ('bill_to', models.CharField(choices=[('Customer', 'Customer'), ('Company', 'Company')], default='Company', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
    ]
