# Generated by Django 4.2.27 on 2026-07-19 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0046_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='expense',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_allocations', to='marania_invoice_app.expense'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_allocations', to='marania_invoice_app.invoice', to_field='invoice_number'),
        ),
    ]
