# Generated by Django 4.2.27 on 2026-07-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0047_paymentallocation_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingbalance',
            name='account_id',
        ),
    ]
