# Generated by Django 4.2.27 on 2026-07-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0048_remove_openingbalance_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingbalance',
            name='ob_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
