# Generated by Django 4.2.27 on 2026-07-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0049_openingbalance_ob_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingbalance',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='openingbalance',
            name='debit_amount',
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='balance_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=10),
        ),
    ]
