# Generated by Django 4.2.27 on 2026-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0052_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('pl_key', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sales_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inhouse_material_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_loss_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_loss_status', models.CharField(default='NO PROFIT / NO LOSS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', '-pl_key'],
            },
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit',
            field=models.CharField(choices=[('number', 'Number'), ('meter', 'Meter'), ('KG', 'KG')], default='KG', max_length=10),
        ),
    ]
