# Generated by Django 4.2.27 on 2026-07-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0053_profitloss'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profitloss',
            unique_together={('month', 'year')},
        ),
    ]
