# Generated by Django 4.2.27 on 2026-07-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0054_alter_profitloss_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwineInventory',
            fields=[
                ('ti_key', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('twine', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('waste_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_usage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usage_basis', models.CharField(default='Average', max_length=50)),
                ('days_left', models.IntegerField(blank=True, null=True)),
                ('est_stock_out_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', '-ti_key'],
                'unique_together': {('month', 'year', 'twine')},
            },
        ),
    ]
