# Generated by Django 4.2.27 on 2026-07-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0055_twineinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
