# Generated by Django 4.2.27 on 2026-07-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0056_add_invoice_no_to_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
