# Generated by Django 4.2.27 on 2026-07-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0058_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('ProductionQueue', 'P.Queue'), ('InProduction', 'In Prod'), ('ProductionCompleted', 'P.Completed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('OnHold', 'On Hold'), ('Rejected', 'Rejected')], default='Ordered', max_length=30),
        ),
    ]
