# Generated by Django 4.2.27 on 2026-08-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0059_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='display_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
