# Generated by Django 4.2.27 on 2026-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0061_paymentreceipt_display_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingbalance',
            name='display_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
