# Generated by Django 4.2.27 on 2026-08-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0062_openingbalance_display_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='material_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
