# Generated by Django 4.2.27 on 2026-08-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0063_purchase_material_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transportation_cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packing_cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Additional Cost',
                'verbose_name_plural': 'Additional Costs',
            },
        ),
        migrations.CreateModel(
            name='MachineOperationalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=50, unique=True)),
                ('number_of_shuttles', models.IntegerField()),
                ('running_product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('operator_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bobbin_winder_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mending_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mechanic_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miscellaneous_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['machine_number'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConversionRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, unique=True)),
                ('conversion_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['material_code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, unique=True)),
                ('processing_cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('small_size_cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['material_code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='twineinventory',
            unique_together=set(),
        ),
    ]
