# Generated by Django 4.2.27 on 2026-08-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0064_additionalcost_machineoperationalcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconversionratio',
            name='conversion_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
