# Generated by Django 4.2.27 on 2026-08-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0065_alter_materialconversionratio_conversion_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('production_key', models.AutoField(primary_key=True, serialize=False)),
                ('production_date', models.DateField(default='today')),
                ('customer', models.CharField(max_length=255)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('mm', models.CharField(blank=True, max_length=50, null=True)),
                ('md', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('sel', models.CharField(blank=True, max_length=50, null=True)),
                ('pw', models.CharField(blank=True, max_length=50, null=True)),
                ('required_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('machine', models.CharField(blank=True, max_length=50, null=True)),
                ('selvage_twine', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_times', models.IntegerField(default=1)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('calculated_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='marania_invoice_app.order')),
            ],
            options={
                'ordering': ['-production_date', '-production_key'],
            },
        ),
    ]
