# Generated by Django 4.2.27 on 2026-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0066_production_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineoperationalcost',
            name='knots_capacity_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
