# Generated by Django 4.2.27 on 2026-08-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0067_knots_capacity_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='number_of_times',
        ),
        migrations.RemoveField(
            model_name='production',
            name='selvage_twine',
        ),
        migrations.AddField(
            model_name='production',
            name='addl_net_twine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='knots_capacity_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='quantity_unit',
            field=models.CharField(default='KG', max_length=20),
        ),
        migrations.AddField(
            model_name='production',
            name='total_meshes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='total_twine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
