# Generated by Django 4.2.27 on 2026-08-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0068_remove_production_number_of_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='est_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
