# Generated by Django 4.2.27 on 2026-08-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0069_production_est_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='required_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='total_daily_output',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
