# Generated by Django 4.2.27 on 2026-08-10 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0070_production_analysis_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitAnalytics',
            fields=[
                ('profit_key', models.AutoField(primary_key=True, serialize=False)),
                ('profit_date', models.DateField(default='today')),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('machine', models.CharField(blank=True, max_length=50, null=True)),
                ('est_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_daily_output', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('required_days', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('machine_operational_cost_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('machine_operational_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('processing_cost_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('processing_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_cost_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('raw_material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_analytics', to='marania_invoice_app.production')),
            ],
            options={
                'ordering': ['-profit_date', '-profit_key'],
            },
        ),
    ]
