# Generated by Django 4.2.27 on 2026-08-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0071_profit_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitanalytics',
            name='raw_twine_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
