# Generated by Django 4.2.27 on 2026-08-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0072_profit_raw_twine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalcost',
            name='waste_cost_per_kg',
        ),
        migrations.AddField(
            model_name='additionalcost',
            name='waste_percentage',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
    ]
