# Generated by Django 4.2.27 on 2026-08-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0073_remove_additionalcost_waste_cost_per_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='required_days',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profitanalytics',
            name='required_days',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
