# Generated by Django 4.2.27 on 2026-08-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0075_profitanalytics_color_cost_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitanalytics',
            name='profit_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
