# Generated by Django 4.2.27 on 2026-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0076_add_profit_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceWeightAnalyser',
            fields=[
                ('pwa_key', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('mm', models.CharField(blank=True, max_length=50, null=True)),
                ('md', models.CharField(blank=True, max_length=50, null=True)),
                ('sel', models.CharField(blank=True, max_length=50, null=True)),
                ('pw', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('addl_mesh_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('groups_data', models.TextField(blank=True, null=True)),
                ('exp_piece_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('knot_count', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pcs', models.IntegerField(blank=True, null=True)),
                ('all_pcs_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-pwa_key'],
            },
        ),
    ]
