# Generated by Django 4.2.27 on 2026-08-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0077_pieceweightanalyser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceweightanalyser',
            name='all_specs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pieceweightanalyser',
            name='order_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pieceweightanalyser',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
