# Generated by Django 4.2.27 on 2026-08-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0078_add_pwa_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceweightanalyser',
            name='order_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
