# Generated by Django 4.2.27 on 2026-08-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0079_add_pwa_order_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementInvoice',
            fields=[
                ('settlement_id', models.AutoField(primary_key=True, serialize=False)),
                ('settlement_invoice_number', models.CharField(max_length=50, unique=True)),
                ('settlement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settlement_invoices', to='marania_invoice_app.parties')),
            ],
            options={
                'ordering': ['-settlement_date', '-settlement_id'],
            },
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='settlement_invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_allocations', to='marania_invoice_app.settlementinvoice'),
        ),
    ]
