# Generated by Django 4.2.27 on 2026-08-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0080_settlementinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementinvoice',
            name='display_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
