# Generated by Django 4.2.27 on 2026-08-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0081_settlementinvoice_display_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialconversionratio',
            name='base_conversion_ratio',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='materialconversionratio',
            name='multiplier',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
        ),
    ]
