# Generated by Django 4.2.27 on 2026-08-23 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0082_materialconversionratio_base_conversion_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='small_mesh_size',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='colour_charge',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='small_mesh_size_charge',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.CreateModel(
            name='PriceListConfiguration',
            fields=[
                ('price_list_key', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('twine_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_included', models.BooleanField(default=False)),
                ('colour_price', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('small_mesh_size', models.PositiveIntegerField(default=50)),
                ('small_mesh_price', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('daily_profit_values', models.TextField(default='[]')),
                ('mesh_size_ranges', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_list_configs', to='marania_invoice_app.product', to_field='code')),
            ],
        ),
    ]
