# Generated by Django 4.2.27 on 2026-08-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0083_companysettings_small_mesh_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistconfiguration',
            name='machine_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pricelistconfiguration',
            name='mesh_depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
