# Generated by Django 4.2.27 on 2026-08-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0084_pricelistconfiguration_machine_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingcost',
            name='small_mesh_depth_starting_depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
