# Generated by Django 4.2.27 on 2026-08-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0085_processingcost_small_mesh_depth_starting_depth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingcost',
            old_name='small_size_cost_per_kg',
            new_name='small_depth_size_cost_per_kg',
        ),
        migrations.RenameField(
            model_name='profitanalytics',
            old_name='small_size_cost_per_kg',
            new_name='small_depth_size_cost_per_kg',
        ),
        migrations.RemoveField(
            model_name='processingcost',
            name='small_mesh_depth_starting_depth',
        ),
        migrations.AddField(
            model_name='processingcost',
            name='small_depth_starting_depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
