# Generated by Django 4.2.27 on 2026-08-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0087_rename_fields_pricelistconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='colour_charge',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='small_mesh_size',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='small_mesh_size_charge',
        ),
    ]
