# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0088_remove_company_settings_mesh_colour_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_bag_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
