# Generated by Django 4.2.27 on 2026-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0090_add_specification_to_profitanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='extra_mesh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
