# Generated by Django 4.2.27 on 2026-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0091_production_extra_mesh'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraMeshConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_max', models.DecimalField(decimal_places=2, help_text='Upper bound of MM range', max_digits=10, unique=True)),
                ('extra_mesh', models.DecimalField(decimal_places=2, help_text='Extra Mesh value for this range', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extra Mesh Configuration',
                'verbose_name_plural': 'Extra Mesh Configurations',
                'ordering': ['mm_max'],
            },
        ),
    ]
