# Generated by Django 4.2.27 on 2026-08-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0092_extrameshconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListColourConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_colour', models.CharField(help_text='Base colour name, e.g. Green, Blue, Orange', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='price_list_colours', to='marania_invoice_app.product', to_field='code', unique=True)),
            ],
            options={
                'verbose_name': 'Price List Colour Configuration',
                'verbose_name_plural': 'Price List Colour Configurations',
            },
        ),
    ]
