# Generated by Django 4.2.27 on 2026-08-27 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marania_invoice_app', '0093_pricelistcolourconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistcolourconfiguration',
            name='product',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='price_list_colours', to='marania_invoice_app.product', to_field='code'),
        ),
    ]
