# Generated by Django 4.2.27 on 2026-08-28 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marania_invoice_app', '0094_alter_pricelistcolourconfiguration_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique identifier, e.g. 'transaction_orders'.", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Human-readable name, e.g. 'Orders'.", max_length=100)),
                ('url_prefix', models.CharField(blank=True, help_text="URL prefix (e.g. '/orders') that gates access to this module.", max_length=200, null=True)),
                ('icon_name', models.CharField(blank=True, help_text='Feather icon name.', max_length=50, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_all_modules', models.BooleanField(default=False, help_text='Grant access to all current and future modules.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modules', models.ManyToManyField(blank=True, help_text='Modules this category can access by default.', related_name='categories', to='marania_invoice_app.applicationmodule')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo shown on the login screen and branding.', null=True, upload_to='company/logo'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='login_company_name',
            field=models.CharField(blank=True, help_text='Application / company name shown on the login screen. Defaults to Company Name.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='login_footer_text',
            field=models.CharField(blank=True, help_text='Optional footer text (e.g. copyright) on the login screen.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='login_instructions',
            field=models.TextField(blank=True, default='Please sign in with your assigned username and password to continue.', help_text='Instructional text displayed on the login screen.', null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='login_welcome_message',
            field=models.CharField(blank=True, default='Welcome back', help_text='Primary welcome text shown on the login screen.', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='marania_invoice_app.usercategory')),
                ('modules', models.ManyToManyField(blank=True, help_text='Additional modules granted to this user (may supplement the category).', related_name='profiles', to='marania_invoice_app.applicationmodule')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('DEACTIVATE', 'Deactivate'), ('ACTIVATE', 'Activate'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_CHANGE', 'Password Change'), ('LOGIN_FAIL', 'Login Failed'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERMISSION', 'Permission Change'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_label', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
